name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Lint
        run: pnpm lint
      - name: Typecheck
        run: pnpm typecheck
      - name: Build shared SDKs
        run: |
          pnpm --filter @ma/contracts build
          pnpm --filter @ma/identity-client build
      - name: Identity tests
        run: pnpm test:identity
      - name: Portal tests
        run: pnpm test:portal
      - name: Admin tests
        run: pnpm test:admin
      - name: Tasks tests
        run: pnpm test:tasks
      - name: Worker tests
        run: pnpm test:worker
      - name: Build identity & apps
        run: |
          pnpm build:identity
          pnpm build:portal
          pnpm build:admin
          pnpm build:tasks
          pnpm build:worker
